import assert from 'node:assert/strict'
import { readFileSync, existsSync } from 'node:fs'

const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
const comparisonsPath = new URL('../src/pages/DataComparisons.tsx', import.meta.url)
const profilesPath = new URL('../src/pages/DataComparisonProfiles.tsx', import.meta.url)

assert.ok(app.includes("'data-comparisons'"), 'App Page union should include data-comparisons')
assert.ok(app.includes("'data-comparison-profiles'"), 'App Page union should include data-comparison-profiles')
assert.ok(app.includes('DataComparisons'), 'App should import and render DataComparisons page')
assert.ok(app.includes('DataComparisonProfiles'), 'App should import and render DataComparisonProfiles page')
assert.ok(app.includes('Сверка данных'), 'Navigation should show Сверка данных')
assert.ok(app.includes('Профили сверки'), 'Navigation should show Профили сверки as a separate sidebar section')
assert.ok(existsSync(comparisonsPath), 'DataComparisons page should exist')
assert.ok(existsSync(profilesPath), 'DataComparisonProfiles page should exist')

const comparisonsPage = readFileSync(comparisonsPath, 'utf8')
assert.ok(comparisonsPage.includes('/api/data-comparisons/profiles'), 'Run page should load comparison profiles')
assert.ok(comparisonsPage.includes('/api/data-comparisons/runs'), 'Run page should create/list comparison runs')
assert.ok(comparisonsPage.includes('Дата с'), 'Run page should let user choose date_from')
assert.ok(comparisonsPage.includes('Дата по'), 'Run page should let user choose date_to')
assert.ok(comparisonsPage.includes('Профиль сверки'), 'Run page should require profile selection')
assert.ok(comparisonsPage.includes('Строка начала'), 'Run page should configure first checked row per run')
assert.ok(comparisonsPage.includes('Строка окончания'), 'Run page should configure last checked row per run')
assert.ok(!comparisonsPage.includes('Создать профиль сверки'), 'Run page should not include profile creation form')
assert.ok(comparisonsPage.includes('found_in_yms_extended_period'), 'Run page should show ±2 days diagnostic status')

const profilesPage = readFileSync(profilesPath, 'utf8')
assert.ok(profilesPage.includes('Профили сверки'), 'Profiles page should have its own title')
assert.ok(profilesPage.includes('Создать профиль'), 'Profiles page should create profiles')
assert.ok(profilesPage.includes('Редактировать'), 'Profiles page should allow profile editing')
assert.ok(profilesPage.includes('Сохранить'), 'Profiles page should save profile edits')
assert.ok(profilesPage.includes('/api/data-comparisons/profiles'), 'Profiles page should use profiles API')
assert.ok(profilesPage.includes('axios.put'), 'Profiles page should update profiles via PUT')
assert.ok(!profilesPage.includes('Строка начала'), 'Profiles page should not treat checked row range as profile settings')
assert.ok(!profilesPage.includes('Строка окончания'), 'Profiles page should not treat checked row range as profile settings')
