import assert from 'node:assert/strict'
import { readFileSync, existsSync } from 'node:fs'

const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
const comparisonsPath = new URL('../src/pages/DataComparisons.tsx', import.meta.url)
const profilesPath = new URL('../src/pages/DataComparisonProfiles.tsx', import.meta.url)

assert.ok(app.includes("'data-comparisons'"), 'App Page union should include data-comparisons')
assert.ok(app.includes("'data-comparison-profiles'"), 'App Page union should include data-comparison-profiles')
assert.ok(app.includes('DataComparisons'), 'App should import and render DataComparisons page')
assert.ok(app.includes('DataComparisonProfiles'), 'App should import and render DataComparisonProfiles page')
assert.ok(app.includes('Сверка данных'), 'Navigation should show Сверка данных')
assert.ok(app.includes('Профили сверки'), 'Navigation should show Профили сверки as a separate sidebar section')
assert.ok(existsSync(comparisonsPath), 'DataComparisons page should exist')
assert.ok(existsSync(profilesPath), 'DataComparisonProfiles page should exist')

const comparisonsPage = readFileSync(comparisonsPath, 'utf8')
assert.ok(comparisonsPage.includes('/api/data-comparisons/profiles'), 'Run page should load comparison profiles')
assert.ok(comparisonsPage.includes('/api/data-comparisons/runs'), 'Run page should create/list comparison runs')
assert.ok(comparisonsPage.includes('Дата с'), 'Run page should let user choose date_from')
assert.ok(comparisonsPage.includes('Дата по'), 'Run page should let user choose date_to')
assert.ok(comparisonsPage.includes('Профиль сверки'), 'Run page should require profile selection')
assert.ok(comparisonsPage.includes('Строка начала'), 'Run page should configure first checked row per run')
assert.ok(comparisonsPage.includes('Строка окончания'), 'Run page should configure last checked row per run')
assert.ok(!comparisonsPage.includes('Создать профиль сверки'), 'Run page should not include profile creation form')
assert.ok(comparisonsPage.includes('found_in_yms_extended_period'), 'Run page should show ±2 days diagnostic status')
assert.ok(comparisonsPage.includes('Столбцы YMS'), 'Result viewer should show YMS extra columns as a dropdown control')
assert.ok(comparisonsPage.includes('Столбцы из файла'), 'Result viewer should show uploaded-file columns as a separate dropdown control')
assert.ok(comparisonsPage.includes('myBookingExtraColumns'), 'Result viewer should limit YMS extra columns to MyBookings fields')
assert.ok(comparisonsPage.includes('ymsColumnsDropdownOpen'), 'Result viewer should toggle the YMS extra-column dropdown')
assert.ok(comparisonsPage.includes('fileColumnsDropdownOpen'), 'Result viewer should toggle the uploaded-file column dropdown')
assert.ok(comparisonsPage.includes('selectedYmsColumns'), 'Result viewer should track selected YMS columns separately')
assert.ok(comparisonsPage.includes('selectedFileColumns'), 'Result viewer should track selected uploaded-file columns separately')
assert.ok(comparisonsPage.includes('booking_date'), 'Result viewer should offer MyBookings date field')
assert.ok(comparisonsPage.includes('dock_name'), 'Result viewer should offer MyBookings dock field')
assert.ok(comparisonsPage.includes('supplier_name'), 'Result viewer should offer MyBookings supplier field')
assert.ok(comparisonsPage.includes('user_full_name'), 'Result viewer should offer MyBookings user field')
assert.ok(comparisonsPage.includes('yms_data'), 'Result viewer should read selectable columns from YMS booking data')
assert.ok(comparisonsPage.includes('file_data'), 'Result viewer should read selectable columns from the uploaded-file snapshot')
assert.ok(comparisonsPage.includes('buildAvailableFileColumns'), 'Result viewer should build selectable uploaded-file columns from saved file_data fields')
assert.ok(comparisonsPage.includes('moveResultColumn'), 'Result viewer should support moving result columns by drag and drop')
assert.ok(comparisonsPage.includes('onDragStart'), 'Result table headers should start column drag operations')
assert.ok(comparisonsPage.includes('onDrop'), 'Result table headers should accept dropped columns')
assert.ok(comparisonsPage.includes('draggable'), 'Result table headers should be draggable')
assert.ok(comparisonsPage.includes('Перетащите заголовок столбца'), 'Result viewer should explain that table columns can be reordered')
assert.ok(comparisonsPage.includes('comparison-hero'), 'Data comparisons section should have a redesigned hero/header area')
assert.ok(comparisonsPage.includes('comparison-toolbar'), 'Result controls should be visually grouped into a toolbar')
assert.ok(comparisonsPage.includes('comparison-column-menu'), 'Column selector dropdowns should use the redesigned column menu styling')
assert.ok(comparisonsPage.includes('comparison-result-table'), 'Result table should use dedicated comparison table styling')
assert.ok(!comparisonsPage.includes('collectExtraFields'), 'Result viewer should not expose every returned field via the old combined collector')

const profilesPage = readFileSync(profilesPath, 'utf8')
assert.ok(profilesPage.includes('Профили сверки'), 'Profiles page should have its own title')
assert.ok(profilesPage.includes('Создать профиль'), 'Profiles page should create profiles')
assert.ok(profilesPage.includes('Редактировать'), 'Profiles page should allow profile editing')
assert.ok(profilesPage.includes('Сохранить'), 'Profiles page should save profile edits')
assert.ok(profilesPage.includes('/api/data-comparisons/profiles'), 'Profiles page should use profiles API')
assert.ok(profilesPage.includes('axios.put'), 'Profiles page should update profiles via PUT')
assert.ok(profilesPage.includes('Колонки Excel для снимка'), 'Profiles page should configure saved Excel snapshot columns')
assert.ok(profilesPage.includes('snapshot_columns'), 'Profiles page should persist snapshot_columns in file_settings')
assert.ok(profilesPage.includes('A:C,E'), 'Profiles page should show range/list examples such as A:C,E')
assert.ok(!profilesPage.includes('Строка начала'), 'Profiles page should not treat checked row range as profile settings')
assert.ok(!profilesPage.includes('Строка окончания'), 'Profiles page should not treat checked row range as profile settings')
