"""add booking_type to bookings

Revision ID: b674c34706ca
Revises: 7f1f88b04543
Create Date: 2026-01-14 07:30:56.116656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b674c34706ca'
down_revision: Union[str, None] = '7f1f88b04543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_type', sa.Enum('in', 'out', name='bookingdirection'), server_default='in', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'booking_type')
    # ### end Alembic commands ###
