"""add supplier transport type association

Revision ID: d074798221ed
Revises: 751adef49752
Create Date: 2025-12-28 10:59:01.012705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd074798221ed'
down_revision: Union[str, None] = '751adef49752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('suppliers_transport_type_id_fkey', 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'transport_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('transport_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('suppliers_transport_type_id_fkey', 'suppliers', 'transport_types', ['transport_type_id'], ['id'])
    # ### end Alembic commands ###
