"""Add Object, PrrLimit models and update Dock, Supplier
Revision ID: f6402659de40
Revises: 
Create Date: 2025-12-20 11:22:35.842793
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6402659de40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("COMMIT")
    op.execute("CREATE TYPE objecttype AS ENUM ('warehouse', 'production', 'retail', 'pickup_point', 'other');")

    op.create_table('objects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('object_type', sa.Enum('warehouse', 'production', 'retail', 'pickup_point', 'other', name='objecttype'), nullable=False),
        sa.Column('address', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    op.bulk_insert(sa.table('objects',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('object_type', sa.String),
        sa.column('address', sa.String),
    ),
        [
            {'id': 1, 'name': 'Обухово', 'object_type': 'warehouse', 'address': '142440, МО, Ногинский р-н, п. Обухово, Кудиновское ш., д. 4'},
            {'id': 2, 'name': 'Аксон', 'object_type': 'warehouse', 'address': 'Ногинский р-н, п. Аксено-Бутырское'},
        ]
    )
    
    op.create_table('dock_zone_association',
        sa.Column('dock_id', sa.Integer(), nullable=False),
        sa.Column('zone_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['dock_id'], ['docks.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('dock_id', 'zone_id')
    )

    op.create_table('dock_transport_type_association',
        sa.Column('dock_id', sa.Integer(), nullable=False),
        sa.Column('transport_type_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['dock_id'], ['docks.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['transport_type_id'], ['transport_types.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('dock_id', 'transport_type_id')
    )

    op.create_table('prr_limits',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('object_id', sa.Integer(), nullable=False),
        sa.Column('supplier_id', sa.Integer(), nullable=True),
        sa.Column('transport_type_id', sa.Integer(), nullable=True),
        sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
        sa.ForeignKeyConstraint(['transport_type_id'], ['transport_types.id'], ),
        sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('object_id', 'supplier_id', 'transport_type_id', 'vehicle_type_id', name='_object_supplier_transport_vehicle_uc')
    )

    op.add_column('docks', sa.Column('object_id', sa.Integer(), nullable=True))
    op.execute('UPDATE docks SET object_id = 1')
    op.alter_column('docks', 'object_id', nullable=False)

    op.drop_constraint('docks_zone_id_fkey', 'docks', type_='foreignkey')
    op.create_foreign_key('docks_object_id_fkey', 'docks', 'objects', ['object_id'], ['id'])
    op.drop_column('docks', 'zone_id')
    
    op.add_column('suppliers', sa.Column('transport_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key('suppliers_transport_type_id_fkey', 'suppliers', 'transport_types', ['transport_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('suppliers_transport_type_id_fkey', 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'transport_type_id')

    op.add_column('docks', sa.Column('zone_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('docks_object_id_fkey', 'docks', type_='foreignkey')
    op.create_foreign_key('docks_zone_id_fkey', 'docks', 'zones', ['zone_id'], ['id'])
    op.drop_column('docks', 'object_id')
    
    op.drop_table('prr_limits')
    op.drop_table('dock_transport_type_association')
    op.drop_table('dock_zone_association')
    op.drop_table('objects')
    
    op.execute("DROP TYPE IF EXISTS objecttype CASCADE")
    # ### end Alembic commands ###

