"""Make vehicle_plate, driver_full_name, driver_phone nullable
Revision ID: make_booking_fields_nullable
Revises: f6402659de40
Create Date: 2026-01-03 10:21:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'make_booking_fields_nullable'
down_revision: Union[str, None] = 'f6402659de40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'vehicle_plate',
               existing_type=sa.String(length=20),
               nullable=True)
    op.alter_column('bookings', 'driver_full_name',
               existing_type=sa.String(length=150),
               nullable=True)
    op.alter_column('bookings', 'driver_phone',
               existing_type=sa.String(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'driver_phone',
               existing_type=sa.String(length=30),
               nullable=False)
    op.alter_column('bookings', 'driver_full_name',
               existing_type=sa.String(length=150),
               nullable=False)
    op.alter_column('bookings', 'vehicle_plate',
               existing_type=sa.String(length=20),
               nullable=False)
    # ### end Alembic commands ###